trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

variables:
  JAVA_HOME: '/usr/lib/jvm/zulu-17-azure-amd64'
  MAVEN_OPTS: '-Xmx1024m'
  PGPASSWORD: '123sqldb'  # Set PostgreSQL password as an environment variable

steps:
- task: JavaToolInstaller@0
  inputs:
    versionSpec: '17'
    jdkArchitectureOption: 'x64'
    jdkSourceOption: 'PreInstalled'
    jdkDestinationDirectory: '$(JAVA_HOME)'

- task: Maven@3
  inputs:
    mavenPomFile: 'pom.xml'
    goals: 'clean install'
    options: '--batch-mode -e -X'  # Enable detailed logging
    publishJUnitResults: true
    testResultsFiles: '**/target/surefire-reports/TEST-*.xml'
    javaHomeOption: 'JDKVersion'
    jdkVersionOption: '1.17'
    mavenVersionOption: 'Default'
    mavenAuthenticateFeed: false
    effectivePomSkip: false
    sonarQubeRunAnalysis: false
  displayName: 'Build and Test with Maven'

- task: CopyFiles@2
  inputs:
    contents: 'target/surefire-reports/**'
    targetFolder: '$(Build.ArtifactStagingDirectory)/surefire-reports'

- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)/surefire-reports'
    ArtifactName: 'surefire-reports'

- task: CopyFiles@2
  inputs:
    contents: 'target/*.jar'
    targetFolder: '$(Build.ArtifactStagingDirectory)'

- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)'
    ArtifactName: 'drop'

# Install PostgreSQL client
- script: |
    sudo apt-get update
    sudo apt-get install -y postgresql-client
  displayName: 'Install PostgreSQL client'

# Execute SQL scripts
- script: |
    psql -h localhost -U sql99 -d mydatabase -a -f ./scripts.sql
  displayName: 'Run SQL Scripts'
  env:
    PGPASSWORD: $(PGPASSWORD)  # Use the environment variable for the password
