pool:
  vmImage: 'ubuntu-latest'

steps:
- task: JavaToolInstaller@0
  inputs:
    versionSpec: '17'
    jdkArchitectureOption: 'x64'
    jdkSourceOption: 'PreInstalled'
    jdkDestinationDirectory: '/usr/lib/jvm/zulu-17-azure-amd64'

- task: Maven@3
  inputs:
    mavenPomFile: 'pom.xml'
    goals: 'clean install'
    options: '--batch-mode -e -X'
    publishJUnitResults: true
    testResultsFiles: '**/target/surefire-reports/TEST-*.xml'
    javaHomeOption: 'JDKVersion'
    jdkVersionOption: '1.17'
    mavenVersionOption: 'Default'
    mavenAuthenticateFeed: false
    effectivePomSkip: false
    sonarQubeRunAnalysis: false
  displayName: 'Build and Test with Maven'

- task: CopyFiles@2
  inputs:
    contents: 'target/surefire-reports/**'
    targetFolder: '$(Build.ArtifactStagingDirectory)/surefire-reports'

- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)/surefire-reports'
    ArtifactName: 'surefire-reports'

- task: CopyFiles@2
  inputs:
    contents: 'target/*.jar'
    targetFolder: '$(Build.ArtifactStagingDirectory)'

- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)'
    ArtifactName: 'drop'

# Install PostgreSQL client
- script: |
    sudo apt-get update
    sudo apt-get install -y postgresql-client
  displayName: 'Install PostgreSQL client'

# Execute SQL scripts
- script: |
    psql -h localhost -d mydatabase -a -f ./path/to/your/sql/script.sql
  displayName: 'Run SQL Scripts'
